apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gsoc-device-plugin-ds
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: gsoc-device-plugin
        app: gpu
        name: gsoc-device-plugin-ds
    spec:
      # TODO change this name
      serviceAccount: gpushare-device-plugin
      hostNetwork: true
      nodeSelector:
      # TODO change this name
        gpushare: "true"
      containers:
      - image: gsoc:lijj
        imagePullPolicy: Never
        name: gpu
        # Make this pod as Guaranteed pod which will never be evicted because of node's resource consumption.
        command:
          - gsoc-device-plugin
          - -logtostderr
          - --v=5
          - --memory-unit=GiB
        resources:
          limits:
            memory: "300Mi"
            cpu: "1"
          requests:
            memory: "300Mi"
            cpu: "1"
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/kubelet.conf
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins